// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:06788ecb-7142-4f13-9a21-927b7cb67151",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Tw7W5AmAS",
    "aws_user_pools_web_client_id": "24furps1iepkut3ajpo7firfg7",
    "oauth": {},
    "aws_user_files_s3_bucket": "streamstoragestream-stream",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "hostingbucket-stream-stream",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://hostingbucket-stream-stream.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
